### ISSUE TITLE
This repo looks defunct: but prove me wrong :)

### ISSUE THREAD

**Issue by boxabirds** [sugarme/transformer#13]
This looks really great! But 6 months of silence -- meanwhile transformers.py has made huge headways -- suggests this has fallen into disuse and is no longer active. But I hope I'm wrong!

**Comment by sugarme** [comment]
@boxabirds ,

This repo is just demonstrates how to compose transformer with gotch in Go. There will be an update to get it work in the latest libtorch and gotch version though.
