### ISSUE TITLE
Example in readme gives wrong output

### ISSUE THREAD

**Issue by wujunfeng1** [sugarme/transformer#6]
The following statement in basic example of README.md:

encodings, err := tk.EncodeBatch(input, true)

could cause two different encodings as described in tokenizer/tokenizer.go: 
"EncodeBatch encodes all sentences in concurrency".
In fact, the EncodeBatch function lets the goroutines to concurrently execute the following action:

encodings = append(encodings, *e)

Therefore, since there are two sentences in the input, the encodings could be of two different orders: {sentence1, sentence2} and {sentence2, sentence1}. It is unmatched to the two statements after:

index1 := output.MustGet(0).MustGet(4).MustArgmax(0, false, false).Int64Values()[0]
index2 := output.MustGet(1).MustGet(7).MustArgmax(0, false, false).Int64Values()[0]

As mentioned above, we could either revise function EncodeBatch to make sure it returns encodings in a correct order, or recorrect the two output statements above to choose the right subtensors.

Hope this helps. I like your work very much.

**Comment by wujunfeng1** [comment]
Hi Sugarme, I have modified your EncodeBatch function by two lines and it seems working:

### func (t *Tokenizer) EncodeBatch(inputs []EncodeInput, addSpecialTokens bool) (retVal []Encoding, err error) {
        // first modification 
        // originally, it is:
        // var encodings []Encoding
	encodings := make([]Encoding, len(inputs))
	var wg sync.WaitGroup

	wg.Add(len(inputs))

	// Encoding concurrently
	for i := 0; i < len(inputs); i++ {
		go func(i int) {
			defer wg.Done()

			e, err := t.Encode(inputs[i], addSpecialTokens)
			if err != nil {
				log.Fatal(err)
			}

                        // second modification
                        // originally, it is:
                        // encodings = append(encodings, *e)
			encodings[i] = *e

		}(i)
	}

	wg.Wait()

	// Do padding if included
	if t.padding != nil {
		PadEncodings(encodings, *t.padding)
	}

	return encodings, nil
}

I am not sure whether my modifications to your code is right because I am a newbie golang programmer. Just share with you what I have found.

**Comment by sugarme** [comment]
@wujunfeng1,

Thanks for the report. Haven't touch this for ages. Fixed the issue in package tokenizer.
