### ISSUE TITLE
"go mod tidy" error from sermo repo

### ISSUE THREAD

**Issue by scottmcmaster** [sugarme/transformer#7]
I was looking to update the repo to work with the "tensorflow" package that has been renamed to "ts" one of the dependency projects but ran into this:

1. Clone the repo.
2. `go mod tidy`

You get a git "invalid version" error because something is trying to pull in github.com/sugarme/sermo@v0.0.0-20200418124113-8a3df5eccc88, and the repo seems to be private or deleted.

**Comment by sugarme** [comment]
@scottmcmaster,

Thanks for your report. Please check out newly commit with go.mod clean-up.
